---
title: "Making a case for the use of digital footprint data for evidence-based policies in response to human mobility changes after COVID-19 in Latin America"
author: 
  - name: \small Francisco Rowe
    affiliation:
      - ref: uol
    corresponding: true
  - name: \small Carmen Cabrera-Arnau
    affiliation:
      - ref: uol
  - name: \small Miguel González-Leonardo
    affiliation:
      - ref: colmex
  - name: \small Andrea Nasuto
    affiliation:
      - ref: uol
  - name: \small Ruth Neville
    affiliation:
      - ref: uol
affiliations: 
  - id: uol
    name: University of Liverpool
    city: Liverpool
  - id: colmex
    name: El Colegio de México
    city: Mexico
abstract: |
  **Abstract**. Text for abstract
format: 
  pdf: 
    mainfont: Helvetica
    fontsize: 10pt
editor: visual
bibliography: refs.bib
editor_options:
  markdown:
    wrap: sentence
---

# Introduction

Digital footprint data (DFD) are increasingly becoming a vital component of the data ecosystem to measure and monitor human mobility.
DFD are digital traces left as a result of social interactions on digital platforms, such as the Internet through web search engines (e.g. Google), social media networks (e.g. Twitter and Facebook), commercial systems in the way of transactions (e.g. payment systems), sensor networks to capture environmental and human changes (e.g. fitness trackers, temperature and sound sensors), and imagery collected via satellites, cameras, drones, CCTV and imaging devices. Digital traces encoding location recorded through Call Detail Records (CDRs), eXtended Detail Records (XDR), Global Positioning System (GPS), Bluetooth and smart card data have been particularly valuable to reconstruct a traceable digital representation of human mobility.

These forms of DFD offer three key opportunities to capture human mobility (1) at higher geographical and temporal granularity; (2) over extensive geographical coverage comprising entire population systems or geographical areas; and (3) in real or near-real time \[REF\]. These attributes have enabled to complement traditional data sources to capture human mobility at various geographically scales, including urban mobility \[REF\], internal migration \[REF\] and international migration \[REF\]

Yet, the use of DFD poses significant challenges. 
These data are a by-product of administrative processes.
They are not collected for research purposes.
Their use involves major conceptual, methodological, data and ethical challenges \[REF\].
For instance, turning raw DFD into actionable, usable information requires significant data engineering, embracing data-driven hypotheses, accounting for data biases, ensuring privacy and anonymity, and integrating and validating the resulting outcomes with external data sources \[REF\].
These challenges to be overcome to unleash the opportunities offered by DFD.

An increasing number of "Data for Good" initiatives have been developed to leverage the potential positive social impact of DFD.
These include data governance, data strategy and data sharing initiatives [@europeancommission.jointresearchcentre.2022].
Data governance initiatives involve efforts focused on the provision of guidance about best practices for the collection, storage, share and use DFD for the social good.
Data strategy initiatives focus on building capacity in civil society by designing data strategies for nonprofits and government agencies, such as Data-Pop Alliance and the Open Data Institute.
Data sharing initiatives entail the creation and facilitation of access to datasets by data providers for organisations seeking to generate data solutions and positive social impact.
These initiatives include [Data for Good at Meta](https://dataforgood.facebook.com/dfg/about) and [Waze Partner Hub](https://www.waze.com/wazeforcities/).

Enabled by these initiatives, the use of DFD seems to have been - much more promising in less developed countries given data scarcity.

-   Discuss how digital footprint data have been used in more developed countries or global north

-   Highlight the limited use of digital footprint data in the global south

-   Aim: Use of digital footprint data for mobility and policy response

-   Argue case for COVID and mobility

-   Structure

# Background

## The impact of COVID-19 on internal population movements

Globally, there is evidence that the COVID-19 pandemic constrained both shorth- and long-distance movements within national boundaries [@nouvellet2021; @gonzález-leonardo2022a; @wang2022; @rowe2023]. Declines were documented across the Global North during the first year of the pandemic, in the United States [@ramani2021], some European countries, Japan and Australia [@rowe2023], from 2.5% in Spain to 8.5% in Australia. Drops mostly occurred when governments implemented non-pharmaceutical interventions, such as stay-at-home requirements, travel restrictions, mobility restrictions, business and school closures. Levels of human mobility within countries, however, recovered pre-pandemic values following the elimination of lockdowns and other stringency measures. Declines on human mobility were attributed to lockdowns, increasing teleworking and restrictions of movements, but also to a loss of labour market dynamism as a consequence of the economic recession during the pandemic [@perales2022]. In addition to evidence in the Global North, drops in internal population movements were also found in Latin American, declining by about 10% during periods of severe stringency measures [@aromí2023]. The highest declines occurred in Bolivia, Ecuador and Argentina, ranging from 16% to 19%, while they did not reach 3% in Paraguay and Venezuela.

In global north countries, the COVID-19 pandemic also modified the patters of internal population movements between large cities and areas with lower population densities [@rowe2023]. Variations were found in the United States [@ramani2021], United Kingdom [@rowe2023; @wang2022], Spain [@gonzález-leonardo2022b; @gonzález-leonardo2022a], Germany [@stawarz2022], Sweden [@vogiazides2022], Norway [@tønnessen2021], Australia [@perales2022] and Japan [@fielding2021, @kotsubo2022]. Net-migration rates in large cities declined in the United States, Germany, Norway, Sweden and Japan during 2020, while they increased in their suburbs. [@ramani2021] called this phenomenon as "donut effect", reflecting a decrease in population inflows to urban centers (urbanization) and a growth of movements from cities to their suburban rings (suburbanization). Nonetheless, there is no evidence of a "donut effect" in the United Kingdom, Spain and Japan, as net-flows in suburbs did not show significant changes. However, inflows to large cities also declined and counterurbanisation movements increased, reflecting unusual population gains in rural areas. In Spain, Sweden, Japan and Germany, holiday town with second homes of wealthy individuals were also found as popular destination for people leaving large cities during the pandemic. It suggests that wealthy populations and professionals who are able to work remotely seems to underpin movements from large cities to areas with lower population densities where they own second residences [@haslag2021; @tønnessen2021].

Despite the above-mentioned changes to the human mobility system during the pandemic, research suggests that pre-existing macro-structures of internal population movement across the rural-urban continuum were not altered, since the majority of movements continued to occur within and between urban areas, and changes are not likely to endure [@rowe2023]. For instance, mobility patterns returned to those registered before the pandemic after the lockdown in the United Kingdom [@rowe2022; @wang2022]. The pandemic caused minor impacts on spatial patterns of internal population movements in Australia, and variations attributed to COVID-19 disappeared in late 2020 [@perales2022]. Urbanisation levels returned to those register prior to the pandemic in Spain when the lockdown ended in mid-2020 [@gonzález-leonardo2022b], although unusually high levels of counterurbanisation persisted over 2021, despite decreasing over the year [@gonzález-leonardo2022a].

Previous work provided a good understanding on how human mobility across the rural-urban hierarchy was affected by the pandemic in the Global North. However, less is known about COVID-19 impacts on movements between cities, suburbs and rural areas in the Global South and the durability of potential changes. Anecdotal evidence, based on small surveys carried out in India [@irudayarajan2020] and South Africa [@ginsburg2022], pointed out that flows from large cities to less populated areas increased due to the return of workers to their hometown, while movements of labour force to cities decreased. Both surveys saw that the economic downturn caused by non-pharmaceutical interventions during the pandemic [@ghosh2020] underpinned declining inflows of workers to cities and increasing returns among people who lost their jobs. The above-mentioned anecdotal evidence suggests that vulnerable populations seem to have played a role in movements to and away from large cities during the pandemic in the Global South.

Nonetheless, a recent study demonstrated that wealthy individuals from large cities in Brazil, Colombia, Indonesia, Mexico, Philippines and South Africa moved to lees populated areas during the first wave of COVID-19 [@lucchini2023]. On average, residents from high-wealthy neighborhoods were 1.5 times more likely to leave cities compared to those from low-wealthy areas. These finding is in line to results in Global North countries. Despite anecdotal evidence suggesting pandemic impacts on the patterns of internal population movements across the rural-urban hierarchy in some Global South countries, lack of data has not allowed for quantifying the magnitude and durability of potential impacts on the human mobility system. To fill the gap, we use Facebook data to analyse the effect of COVID-19 on the patterns of internal population movements in Argentina, Chile, Colombia and Mexico.




## Human mobility across the rural-urban continuum in Latin American countries

Currently, Latin America has the highest urbanization rate in the world after North America, totaling 81% [@UNpopulation19]. It means that the population is highly concentrated across space within Latin American countries, particularly in large cities with more than one million inhabitants, where half of urban residents are settled [@PintoDaCunha02; @lattes2017]. High urbanization rates are due to massive levels of population redistribution from rural settlements to cities until the 1980s, mostly during the fast industrialisation period from early-1950s to late-1970s, when population gains were mainly observed in chief cities [@firebaugh1979; @lattes95; @sobrino12].
Internal population movements in Latin America have been declining since the 1980s, as rural population stocks were depleted [@chávezgalindo2016] and the industrial crisis leaded to deconcentration trends in large cities, such as Santiago de Chile [@gonzálezollino2006) or Mexico City [@sobrino2006], where long distance inflows have declined. In sum, middle size cities became more attractive to internal migrants as a consequence of increasing domestic and foreign investment in export-oriented industries or tourism activities, leading to geographic economic dispersal [@Brea03; @Pérez-Campuzano13; @chávezgalindo2016]. Nowadays, movements between cities dominate the internal migratory system in Latin American countries [@bernard2017; @rodríguez-vignoli2018; @UNpopulation19]. About 80% of internal migrants moved between cities, according to the 2010-11 census round [@rodríguez-vignoli2018]. Medium-sizes cities from 500.000 to 1 million residents showed the highest population gains by internal migration, while large cities with more than 1 million residents registered balanced rates and small cities with less than 500.000 inhabitants lost population by internal mobility [@rodríguez-vignoli2018].

Latin American cities have shown a significant growth in terms of land development in their urban peripheries.  Since the 1970s, large cities, such as Santiago de Chile, Buenos Aires or Mexico City, but also middle and small cities have experienced suburbanisation [@graizbord2007; @chávezgalindo2016]. Suburbanisation flows comprise middle- and high-class families moving from cities to auto-segregated areas in the periphery [@borsdorf2003; @rodríguezvignoli2017]. Low-income individuals also settle in slams across suburbs but, in this case, in those areas where the land cost is cheaper [@janoschka2002; @rodríguezvignoli2017]. Both residents in auto-segregated areas and slams commute daily to cities, mainly for work reasons [@chávezgalindo2016]. Most recently, reurbanisation trends have been identified in central areas due to gentrification dynamics, although suburbanization flows continue to dominate short distance movements [@sobrino12; @chávezgalindo2016]. In this repot, we explore COVID-19 impacts on the patterns of human mobility across the rural-urban continuum in Latin America.

# Data

Description of the Meta-Facebook Data - Population and movement

Description of the COVID stringency data

Description of the WorldPop data


## Meta-Facebook Data

The platform Facebook Data for Good and Meta offers unique advantages for analysing human mobility during crisis or unusual event, such as earthquakes, hurricanes, floods or pandemics. Facebook allows their partners, ONGs, universities, research centers and international organizations, to access near real-time datasets (e.g. Facebook Population During Crisis, Facebook Movements During Crisis, Displacement Maps) for monitoring where people move during hazard events and implement rapid policy responses, such as the provision of basic services and humanitarian assistance. These data are available under institutional request.
Facebook collects information on human mobility from mobile app users who have the Location Services device setting turned on. In the course of providing services to their users, many smartphones and smartphone apps regularly collect precise location information. In the case of Facebook, people have an option of whether or not to provide this information to Facebook [@Facebook2023]. Location data is used to provide a variety of services, including helping people find nearby friends, information about nearby Wi-Fi hotspots, and location-relevant ads. This data also enables targeting of AMBER alerts and prompts to check-in as "safe" after a hazard event. In addition to powering Facebook product features, this location data can provide insights about how populations are affected by hazard events as they happen [@Maas19].

These datasets make use of anonymised and aggregated near real-time data during crisis over several weeks, months or even years, and also historical location data as a baseline period before the event. While the raw data used to produce datasets remains available only to the data owners, the aggregated data, with privacy and security protections, is shared with non-profit organisations and researchers on an ongoing basis in the days and weeks following a hazard event [@Maas19].

## Facebook Population During Crisis and Facebook Movement During Crisis data

In this report, we analyse human mobility during the COVID-19 pandemic using the datasets Coronavirus Disease Prevention Map of Facebook Population During Crisis (Tile Level) and Coronavirus Disease Prevention Map of Facebook Movements During Crisis (Tile Level) to four Latin American countries: Argentina, Chile, Colombia and Mexico. The former dataset allows us to analyse how the number of Facebook users changed across space during the COVID-19 pandemic. The latter, which we focus the analysis on, allows us to analyse how the mobility patterns of Facebook users changed amongst spatial units during COVID-19. These datasets are currently discontinued, as Facebook removes products after 90 days since the last data updated.

The datasets contain data corresponding to a two-year period, starting on the 10th March 2020 and ending in mid-March 2022. Data are temporally aggregated into three 8-hour daily time windows (00:00-08:00, 08:00-16:00 and 16:00-00:00). The datasets also include data for baseline levels before COVID-19 based on a 45-day period ending on the 10th of March of 2020. The baseline is computed using an average for the same time-of-the-day and day-of-the-week in the period preceding the crisis. (e.g., Mondays in the time window 00:00 to 8:00, Wednesdays in the time window 16:00 to 00:00). The data is spatially aggregated into units called Tiles, according to the Bing Maps Tile System developed by Microsoft and its world partitions into square cells at various levels of resolution. Our datasets include levels 13 through 16, where level 13 results in tiles that are about 4.9 x 4.9 km at the Equator.
The Facebook Population data provide information on the number of mobile app users who have the location turned on in each Tile. The location where users spent most time within each 8-hour time window is used to determine their location. The Facebook Movement data capture the number of mobile app users who have the location turned on moving between pairs of origin and destination Tiles. To determine a movement and the origin and destination points, Facebook compare the location where a user spend most time between two subsequent time windows of 8 hours each (e.g., 00:00-8:00 and 8:00-16:00). The Tile where the user spent most time in the first time window corresponds to the origin Tile and the Tile where the user spent most time in the second time window corresponds to the destination Tile. The datasets include a 'quality' score indicating if the difference between crisis and baseline counts is statistically significant (values from -4 to 4). This indicator is computed using the number of standard deviations the count of users during the crisis period is above or below the baseline.

Prior to releasing the above-mentioned datasets, Facebook removes information on personal characteristics of users and applies three techniques to ensure privacy and anonymization and also that precise locations cannot be identified for small population counts in sparsely populated areas. First, if population or movements counts are lower than 10 users within an area in the crisis or in the baseline variable, this information is removed. When both the crisis and the baseline counts are below 10, the entire column is dropped. While removing small counts may lead to an underrepresentation of the population in these places, the geographic distribution of population is still reflected in the data. Second, a small undisclosed amount of random noise is added. Third, spatial smoothing is applied to produce a smooth population count surface using inverse distance-weighted averaging (see [@Maas19] for details).

We distinguish between long distance movement (potentially internal migration), those where users move further than 100 Km, and short distance movements (potentially commuting and daily mobility), those where users move within 100 Km. While this approach allows to approximate internal migration and daily mobility, we cannot fully distinguish between commuting and a permanent or long tesrm change of residence due to the nature of the data.

## Covid-19 stringency data

To understand the level of mobility in the context of the COVID-19 pandemic we use the stringency index as a measure of the level of nonpharmaceutical interventions to COVID-19, such as social distancing and lockdown measures and ranges from 0 to 100, with 100 being the strictest value. The values for the stringency index were retreived from the COVID-19 government response tracker (https://www.bsg.ox.ac.uk/research/research-projects/covid-19-government-response-tracker). For more information, see Hale et al. [@Hale2021].
 
## Worldpop data

An additional data set from WorldPop was used to capture the spatial distribution of population density in the different countries analysed here. The WorlPop dataset is in raster format and contains gridded population data at 1 sqkm resolution.

# Methods

## Classifying Bing tiles according to their population density

Here we aim to understand how the population density at the origin and the destination might influence mobility behaviours. To help characterise the population density between origin and destination, we classify the Bing tiles into 10 discrete categories of population density according to the Jenks natural breaks classification method, hence obtaining a categorisation of Bing tiles a lot more detailed than the traditional binary rural/urban classification.

## Tile-based mobility metrics

We measured changes in the intensity of inflows and outflows, i.e. population flows entering ond leaving every tile respectively. We did this across the urban hierarchy of Argentina, Chile, Colombia and Mexico and for two distinctive months during the course of the COVID-19 pandemic: May 2020 and March 2022. Changes in the number of inflows and outflows are measured as a percentage with respect to the baseline values defined by Meta-Facebook [@Maas19]. Specifically, we computed the percentage change for each inflow and outflow to and from every tile. Then, for each of the 10 population density categories, we obtained boxplots that illustrate the spread of values of percentage change in the intensity of the two types of flows.

Furthermore, we also analysed the evolution of netflows, i.e. the difference in the number of people entering and leaving a location, throughout the whole period of the dataset. The netflows where computed aggregating the movement data by month and by population density class category.

## Local vs long-distance mobility

We computed all the tile-based metrics described above for movements where the Euclidean distance between the origin and the destination location was recorded to be greater than 0 km. Furthermore, we stratified the data into two groups that capture local movements and long-distance mobility, by considering flows where the Euclidean distance betwee nthe origin and the destinaiton locations was below or above 100 km. The rationale for this stratification is that we expect the COVID-19 pandemic to affect mobility differently at different spatial scales.


# Results

## Population movements early 2020 and 2020 following the COVID-19 outbreak

Describe the violin / box plots.
Key points:

-   Decline in mobility following the implementation of COVID-19 stringency measures in early 2020.
    The decline follows a gradient: stronger in the most density areas, smaller in the least dense areas.
    Describe differences across countries and types of moves when relevant.

-   Recovery in 2022 following the relaxation of COVID-19 restrictions.
    Describe differences across countries and types of move when relevant.

## Spatio-temporal patterns of population redistribution during COVID-19

**\> 50km**

-   Negative net balance in the highest density regions of the metropolitan area in early 2020 for Chile - support of urban exodus but temporarily.
    The negative net balance in the highest density araes coincides with increases with positive balances in low density areas (class 2 and 3)

-   Different patterns in Argentina, Colombia and Mexico - a trend of positive net balances coinciding with negative balances in low density areas (class 2 and 3) - particularly in Colombia and Mexico

-   A systematic pattern of negative net balance in medium size cities across all countries (class 7)

-   The temporal patterns in the intensity of outflows and inflows are remarkably similar with differences in magnitude.

    **\< 50km**

-   Negative net balances in the highest density areas of Argentina, Colombia and Mexico - evidence of a donut effect i.e. negative balance in the core of metropolitan cities

-   This pattern coincides with positive balances across different places in the urban hierarchy in these countries.

-   Chile reports a different pattern - relatively little change - remarkable is the large negative balance in class 8.

## Movements from and to capital cities

<!--# We need to see the maps -->

# Discussion

## Summary of key findings

-   Decline in mobility intensity after the outbreak of COVID-19

-   Support of urban exodus for Chile - but temporary - recovery to pre-pandemic levels

-   Donut effect in Argentina, Colombia and Mexico

## Interpretation

## Policy implications

-   for housing, transport and planning

-   for data

# Conclusion

# References
