---
title: "R Notebook"
output: html_notebook
---


```{r}
# data wrangling
library(tidyverse)

# spatial data wrangling
library(sf)

# data visualisation
library(viridis) 

# format data visualisations
library(ggthemes)
library(patchwork)
library(showtext)
library(scales)
library(classInt)

# create maps
library(leaflet)
library(tmap)
library(mapdeck)
library(patchwork)

```


Set font style
```{r}
# clean workspace
rm(list=ls())
# load font
font_add_google("Roboto Condensed", "robotocondensed")
# automatically use showtext to render text
showtext_auto()
```

Theme for maps
```{r}
theme_map <- function(...) {
  theme_tufte() +
  theme(
    text = element_text(family = "robotocondensed", size = 30),
    # remove all axes
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank()
    )
}
```

## need to read this in 4 separate times - 202
```{r}
# 2020 in
df20_in <- readRDS("R:\\data\\outputs\\mexico\\movements\\2020_04_mov.rds") %>% 
  mutate(GEOMETRY = NULL) %>% 
  dplyr::filter(country == "MX") %>% 
  st_as_sf(coords = c("start_lon", "start_lat"), 
                                      crs = 'EPSG:4326')
# 2020 out
df20_out <- readRDS("R:\\data\\outputs\\mexico\\movements\\2020_04_mov.rds") %>% 
  mutate(GEOMETRY = NULL) %>% 
  dplyr::filter(country == "MX") %>% 
  st_as_sf(coords = c("end_lon", "end_lat"), 
                                      crs = 'EPSG:4326')
# 2022 in
df22_in <- readRDS("R:\\data\\outputs\\mexico\\movements\\2022_03_mov.rds") %>% 
  mutate(GEOMETRY = NULL) %>% 
  dplyr::filter(country == "MX") %>% 
  st_as_sf(coords = c("start_lon", "start_lat"), 
                                      crs = 'EPSG:4326')
# 2022 out
df22_out <- readRDS("R:\\data\\outputs\\mexico\\movements\\2022_03_mov.rds") %>% 
  mutate(GEOMETRY = NULL) %>% 
  dplyr::filter(country == "MX") %>% 
  st_as_sf(coords = c("end_lon", "end_lat"), 
                                      crs = 'EPSG:4326')
```

```{r}
# admin boundaries shape
adm_shp <- st_read("R:\\outputs\\maps\\shapefiles\\gadm41_MEX_shp\\gadm41_MEX_2.shp")%>% 
  st_simplify(preserveTopology = T,
              dTolerance = 1000) %>% 
  st_make_valid() %>% 
  st_transform(crs = 'EPSG:4326')

# region shape
region_shp <- st_read("R:\\outputs\\maps\\shapefiles\\gadm41_MEX_shp\\gadm41_MEX_1.shp")%>% 
  st_simplify(preserveTopology = T,
              dTolerance = 1000) %>% 
  st_make_valid() %>% 
  st_transform(crs = 'EPSG:4326')
```


```{r}
# filter for start location as mexico city
df20_out <- df20_out %>%
  filter(start_polygon_name == 'Ciudad De México')

# filter for end location as mexico city
df20_in <- df20_in %>%
    filter(end_polygon_name == 'Ciudad De México')

df22_out <- df22_out %>%
  filter(start_polygon_name == 'Ciudad De México')

df22_in <- df22_in %>%
  filter(end_polygon_name == 'Ciudad De México')
```


```{r}
# different locations have the same polygon name but different geometry, create a single geometry for each polygon name

# df20_in <- df20_in %>%
#   group_by(start_polygon_name) %>%
#   mutate(geometry = st_union(geometry)) %>%
#   ungroup()
# 
# df20_out <- df20_out %>%
#   group_by(end_polygon_name) %>%
#   mutate(geometry = st_union(geometry)) %>%
#   ungroup()
# 
# df22_in <- df22_in %>%
#    group_by(start_polygon_name) %>%
#    mutate(geometry = st_union(geometry)) %>%
#    ungroup()
# # 
#  df22_out <- df22_out %>%
#   group_by(end_polygon_name) %>%
#   mutate(geometry = st_union(geometry)) %>%
#   ungroup()
```

```{r}
# sum of outflows
outflows_df_20 <- df20_out %>% 
  filter(start_polygon_name != end_polygon_name) %>% 
  group_by(start_polygon_name, end_polygon_name, geometry) %>% 
  dplyr::summarise(
    sum_outflow = sum(n_crisis, na.rm = T)) %>% 
  ungroup() 

outflows_df_22 <- df22_out %>% 
  filter(start_polygon_name != end_polygon_name) %>% 
  group_by( geometry) %>% 
  dplyr::summarise(
    sum_outflow = sum(n_crisis, na.rm = T)) %>% 
  ungroup() 

inflows_df_20 <- df20_in %>% 
  filter(start_polygon_name != end_polygon_name) %>% 
  group_by( geometry) %>% 
  dplyr::summarise(
    sum_outflow = sum(n_crisis, na.rm = T)) %>% 
  ungroup() 

inflows_df_22 <- df22_in %>% 
  filter(start_polygon_name != end_polygon_name) %>% 
  group_by( geometry) %>% 
  dplyr::summarise(
    sum_outflow = sum(n_crisis, na.rm = T)) %>% 
  ungroup() 
```


```{r}
# plot boundaries - test 
p <- ggplot() + 
  geom_sf(data = adm_shp,
          color = "gray60", 
          size = 0.1) 

last_plot()
```
```{r}
# check geometry fits into either admin boundaries or region boundaries
p <- p +
  geom_point(data = outflows_df_20,
    aes(geometry = geometry),
    stat = "sf_coordinates"
  ) 
last_plot()
```

```{r}
# assign a year to each
inflows_df_20$year <- '2020'
inflows_df_22$year <- '2022'
outflows_df_20$year <- '2020'
outflows_df_22$year <- '2022'
```


```{r}
# merge dataframes to create total inflows or total outflows
inflows_df <- rbind(inflows_df_20, inflows_df_22)
outflows_df <- rbind(outflows_df_20, outflows_df_22)
```

```{r}
# spatial join to create file for mapping
mob_indicators_1 <- st_join(adm_shp, outflows_df)
mob_indicators_2 <- st_join(adm_shp, inflows_df)
```



```{r}
# remove nas
mob_indicators_1 <- na.omit(mob_indicators_1)
mob_indicators_2 <- na.omit(mob_indicators_2)
```


```{r}
# create classes for the sum of outflows
mob_indicators_1$new_jenk_class <- classify_intervals(mob_indicators_1$sum_outflow, n = 5, style = "quantile", factor = TRUE)
mob_indicators_2$new_jenk_class <- classify_intervals(mob_indicators_2$sum_outflow, n = 5, style = "quantile", factor = TRUE)

# remove brackets and order 
outflow_labels_1 <- levels(mob_indicators_1$new_jenk_class)
outflow_labels_1 <- gsub("^.|.$", "",  outflow_labels_1)
levels(mob_indicators_1$new_jenk_class) <- outflow_labels_1

outflow_labels_2 <- levels(mob_indicators_2$new_jenk_class)
outflow_labels_2 <- gsub("^.|.$", "", outflow_labels_2)
levels(mob_indicators_2$new_jenk_class) <- outflow_labels_2

# change geometry
shp_reg <- adm_shp %>% st_transform(crs = 'EPSG:4326')
```

```{r}

mob_indicators_2_20 <- mob_indicators_2 %>% 
  filter(year == 2020)

inflow_plot_20 <- ggplot(data = mob_indicators_2_20, aes(fill = new_jenk_class )) +
  geom_sf(col = "white", size = .2) + 
  coord_sf() +
  scale_fill_brewer(palette = "PuBu", direction = 1) +
  theme_map() +
  theme(plot.title = element_text(size = 40, face = "bold"),
        legend.position = "right") +
  labs(title = "(a) Mexico City: 2020 Inflows",
       fill = "Number of moves") +
  geom_sf(data = adm_shp,
          col = "gray", 
          size = .7,
          fill = "transparent") 
   # geom_sf(data = mob_indicators_2 %>%
   #           filter(REGION == "Metropolitana de Santiago"),  # Filter for Santiago municipality
   #        aes(fill = "black"),  # Set a custom fill for the highlighted municipality
   #        col = "black",                 # Set the border color for Santiago
   #        size = 1.5,                  # Adjust the border size
   #        fill = "transparent") + 
  # coord_sf(xlim = st_coordinates(bbox_new)[c(1,2),1], 
  #          ylim = st_coordinates(bbox_new)[c(2,3),2]) 


inflow_plot_20

mob_indicators_2_22 <- mob_indicators_2 %>% 
  filter(year == 2022)

inflow_plot_22 <- ggplot(data = mob_indicators_2_22, aes(fill = new_jenk_class )) +
  geom_sf(col = "white", size = .2) + 
  coord_sf() +
  scale_fill_brewer(palette = "PuBu", direction = 1) +
  theme_map() +
  theme(plot.title = element_text(size = 40, face = "bold"),
        legend.position = "right") +
  labs(title = "(b) Mexico City: 2022 Inflows",
       fill = "Number of moves") +
  geom_sf(data = adm_shp,
          col = "gray", 
          size = .7,
          fill = "transparent") 
   # geom_sf(data = mob_indicators_2 %>%
   #           filter(REGION == "Metropolitana de Santiago"),  # Filter for Santiago municipality
   #        aes(fill = "black"),  # Set a custom fill for the highlighted municipality
   #        col = "black",                 # Set the border color for Santiago
   #        size = 0.5,                  # Adjust the border size
   #        fill = "transparent") + 
  # coord_sf(xlim = st_coordinates(bbox_new)[c(1,2),1], 
  #          ylim = st_coordinates(bbox_new)[c(2,3),2]) 


inflow_plot_22


```


          
```{r}
mob_indicators_1_20 <- mob_indicators_1 %>% 
  filter(year == 2020)


outflow_plot_20 <- ggplot(data = mob_indicators_1_20, aes(fill = new_jenk_class )) +
  geom_sf(col = "white", size = .2) + 
  coord_sf() +
  scale_fill_brewer(palette = "OrRd", direction = 1) +
  theme_map() +
  theme(plot.title = element_text(size = 40, face = "bold"),
        legend.position = "right") +
  labs(title = "(c) Mexico City: Outflows 2020",
       fill = "Number of moves") +
  geom_sf(data = adm_shp,
          col = "gray", 
          size = .7,
          fill = "transparent") 
  # geom_sf(data = mob_indicators_1_20 %>%
  #            filter(REGION == "Metropolitana de Santiago"),  # Filter for Santiago municipality
  #         aes(fill = "black"),  # Set a custom fill for the highlighted municipality
  #         col = "black",                 # Set the border color for Santiago
  #         size = 1.5,                  # Adjust the border size
  #         fill = "transparent") +
  # coord_sf(xlim = st_coordinates(bbox_new)[c(1,2),1], 
  #          ylim = st_coordinates(bbox_new)[c(2,3),2]) 

outflow_plot_20

mob_indicators_1_22 <- mob_indicators_1 %>% 
  filter(year == 2022)

outflow_plot_22 <- ggplot(data = mob_indicators_1_22, aes(fill = new_jenk_class )) +
  geom_sf(col = "white", size = .2) + 
  coord_sf() +
  scale_fill_brewer(palette = "OrRd", direction = 1) +
  theme_map() +
  theme(plot.title = element_text(size = 40, face = "bold"),
        legend.position = "right") +
  labs(title = "(d) Mexico City: Outflows 2022",
       fill = "Number of moves") +
  geom_sf(data = adm_shp,
          col = "gray", 
          size = .7,
          fill = "transparent") 
  # geom_sf(data = mob_indicators_1_22 %>%
  #            filter(REGION == "Metropolitana de Santiago"),  # Filter for Santiago municipality
  #         aes(fill = "black"),  # Set a custom fill for the highlighted municipality
  #         col = "black",                 # Set the border color for Santiago
  #         size = 1.5,                  # Adjust the border size
  #         fill = "transparent") +
  # coord_sf(xlim = st_coordinates(bbox_new)[c(1,2),1], 
  #          ylim = st_coordinates(bbox_new)[c(2,3),2]) 

outflow_plot_22


```

```{r}
 plot <- (inflow_plot_20 + inflow_plot_22) / (outflow_plot_20 + outflow_plot_22)
```

```{r}
png("R:\\outputs\\maps\\mex_flows.png", units="in", width=10, height=6, res=300)
plot
dev.off()
```

### using the grid

```{r}
db_20 <- readRDS("R:\\data\\outputs\\mexico\\dataset_to_model\\2020_04.rds")
db_22 <- readRDS("R:\\data\\outputs\\mexico\\dataset_to_model\\2022_04.rds")
```


```{r}
# admin boundaries shape
adm_shp <- st_read("R:\\outputs\\maps\\shapefiles\\gadm41_MEX_shp\\gadm41_MEX_2.shp")%>% 
  st_simplify(preserveTopology = T,
              dTolerance = 1000) %>% 
  st_make_valid() %>% 
  st_transform(crs = 'EPSG:4326')

# region shape
region_shp <- st_read("R:\\outputs\\maps\\shapefiles\\gadm41_MEX_shp\\gadm41_MEX_1.shp")%>% 
  st_simplify(preserveTopology = T,
              dTolerance = 1000) %>% 
  st_make_valid() %>% 
  st_transform(crs = 'EPSG:4326')
```


```{r}
db_20_out <- db_20 %>% 
  filter(start_polygon_name == 'Ciudad De México') 
db_20_in <- db_20 %>% 
  filter(end_polygon_name == 'Ciudad De México') 

db_22_out <- db_22 %>% 
  filter(start_polygon_name == 'Ciudad De México') 
db_22_in <- db_22 %>% 
  filter(end_polygon_name == 'Ciudad De México') 
```


```{r}
grid <- st_read("R:\\data\\populations\\fb_worldpop_aggregation\\data_with_id\\mexico_with_id.shp")
```


```{r}
db_20_out_grid <- merge(grid, db_20_out , by.x = 'id', by.y = c('wp_pop_id_destination'))
db_20_in_grid <- merge(grid, db_20_in , by.x = 'id', by.y = c('wp_pop_id_origin'))

db_22_out_grid <- merge(grid, db_22_out , by.x = 'id', by.y = c('wp_pop_id_destination'))
db_22_in_grid <- merge(grid, db_22_in , by.x = 'id', by.y = c('wp_pop_id_origin'))
```



```{r}
grid_outflows_df_20 <- db_20_out_grid %>% 
  filter(wp_pop_id_origin != id) %>% 
  group_by(wp_pop_id_origin, id, geometry) %>% 
  dplyr::summarise(
    sum_outflow = sum(mov, na.rm = T)) %>% 
  ungroup() 

grid_inflows_df_20 <- db_20_in_grid %>% 
  filter(wp_pop_id_destination != id) %>% 
  group_by(wp_pop_id_destination, id, geometry) %>% 
  dplyr::summarise(
    sum_outflow = sum(mov, na.rm = T)) %>% 
  ungroup() 

grid_outflows_df_22 <- db_22_out_grid %>% 
  filter(wp_pop_id_origin != id) %>% 
  group_by(wp_pop_id_origin, id, geometry) %>% 
  dplyr::summarise(
    sum_outflow = sum(mov, na.rm = T)) %>% 
  ungroup() 

grid_inflows_df_22 <- db_22_in_grid %>% 
  filter(wp_pop_id_destination != id) %>% 
  group_by(wp_pop_id_destination, id, geometry) %>% 
  dplyr::summarise(
    sum_outflow = sum(mov, na.rm = T)) %>% 
  ungroup() 
```
```{r}

# plot boundaries - test 
p <- ggplot() + 
  geom_sf(data = adm_shp,
          color = "gray60", 
          size = 0.1) 

last_plot()
```

```{r}
# check geometry fits into either admin boundaries or region boundaries
p <- p +
  geom_point(data = grid_outflows_df_22,
    aes(geometry = geometry),
    stat = "sf_coordinates"
  ) 
last_plot()
```

```{r}
# assign a year to each
grid_outflows_df_20$year <- '2020'
grid_inflows_df_20$year <- '2020'
grid_outflows_df_22$year <- '2022'
grid_inflows_df_22$year  <- '2022'
```


```{r}
# merge dataframes to create total inflows or total outflows
inflows_df_grid <- rbind(grid_inflows_df_20, grid_inflows_df_22)
outflows_df_grid <- rbind(grid_outflows_df_20, grid_outflows_df_22)
```


```{r}
mob_indicators_out<- st_join(adm_shp, outflows_df_grid)
mob_indicators_in <- st_join(adm_shp, inflows_df_grid)

```

```{r}
as.numeric(mob_indicators_grid$sum_outflow)
```

```{r}
mob_indicators_out <- na.omit(mob_indicators_out)
mob_indicators_in <- na.omit(mob_indicators_in)

# create classes for the sum of outflows
mob_indicators_out$new_jenk_class <- classify_intervals(mob_indicators_out$sum_outflow, n = 5, style = "quantile", factor = TRUE)
mob_indicators_in$new_jenk_class <- classify_intervals(mob_indicators_in$sum_outflow, n = 5, style = "quantile", factor = TRUE)

# remove brackets and order 
outflow_labels_1 <- levels(mob_indicators_out$new_jenk_class)
outflow_labels_1 <- gsub("^.|.$", "",  outflow_labels_1)
levels(mob_indicators_out$new_jenk_class) <- outflow_labels_1

outflow_labels_2 <- levels(mob_indicators_in$new_jenk_class)
outflow_labels_2 <- gsub("^.|.$", "",  outflow_labels_2)
levels(mob_indicators_in$new_jenk_class) <- outflow_labels_2

# change geometry
shp_reg <- adm_shp %>% st_transform(crs = 'EPSG:4326')
```

```{r}
mob_indicators_in_20 <- mob_indicators_in %>% 
  filter(year == 2020)

inflow_plot_20_grid <- ggplot(data = mob_indicators_in_20, aes(fill = new_jenk_class )) +
  geom_sf(col = "white", size = .2) + 
  coord_sf() +
  scale_fill_brewer(palette = "PuBu", direction = 1) +
  theme_map() +
  theme(plot.title = element_text(size = 40, face = "bold"),
        legend.position = "right") +
  labs(title = "(a) Mexico City: 2020 Inflows",
       fill = "Number of moves") +
  geom_sf(data = adm_shp,
          col = "gray", 
          size = .7,
          fill = "transparent") 
   # geom_sf(data = mob_indicators_2 %>%
   #           filter(REGION == "Metropolitana de Santiago"),  # Filter for Santiago municipality
   #        aes(fill = "black"),  # Set a custom fill for the highlighted municipality
   #        col = "black",                 # Set the border color for Santiago
   #        size = 1.5,                  # Adjust the border size
   #        fill = "transparent") + 
  # coord_sf(xlim = st_coordinates(bbox_new)[c(1,2),1], 
  #          ylim = st_coordinates(bbox_new)[c(2,3),2]) 


inflow_plot_20_grid

mob_indicators_in_22 <- mob_indicators_in %>% 
  filter(year == 2022)

inflow_plot_22_grid <- ggplot(data = mob_indicators_in_22, aes(fill = new_jenk_class )) +
  geom_sf(col = "white", size = .2) + 
  coord_sf() +
  scale_fill_brewer(palette = "PuBu", direction = 1) +
  theme_map() +
  theme(plot.title = element_text(size = 40, face = "bold"),
        legend.position = "right") +
  labs(title = "(b) Mexico City: 2022 Inflows",
       fill = "Number of moves") +
  geom_sf(data = adm_shp,
          col = "gray", 
          size = .7,
          fill = "transparent") 
   # geom_sf(data = mob_indicators_2 %>%
   #           filter(REGION == "Metropolitana de Santiago"),  # Filter for Santiago municipality
   #        aes(fill = "black"),  # Set a custom fill for the highlighted municipality
   #        col = "black",                 # Set the border color for Santiago
   #        size = 0.5,                  # Adjust the border size
   #        fill = "transparent") + 
  # coord_sf(xlim = st_coordinates(bbox_new)[c(1,2),1], 
  #          ylim = st_coordinates(bbox_new)[c(2,3),2]) 


inflow_plot_22_grid

```

```{r}
mob_indicators_out_20 <- mob_indicators_out %>% 
  filter(year == 2020)


outflow_plot_20_grid <- ggplot(data = mob_indicators_out_20, aes(fill = new_jenk_class )) +
  geom_sf(col = "white", size = .2) + 
  coord_sf() +
  scale_fill_brewer(palette = "OrRd", direction = 1) +
  theme_map() +
  theme(plot.title = element_text(size = 40, face = "bold"),
        legend.position = "right") +
  labs(title = "(c) Mexico City: Outflows 2020",
       fill = "Number of moves") +
  geom_sf(data = adm_shp,
          col = "gray", 
          size = .7,
          fill = "transparent") 
  # geom_sf(data = mob_indicators_1_20 %>%
  #            filter(REGION == "Metropolitana de Santiago"),  # Filter for Santiago municipality
  #         aes(fill = "black"),  # Set a custom fill for the highlighted municipality
  #         col = "black",                 # Set the border color for Santiago
  #         size = 1.5,                  # Adjust the border size
  #         fill = "transparent") +
  # coord_sf(xlim = st_coordinates(bbox_new)[c(1,2),1], 
  #          ylim = st_coordinates(bbox_new)[c(2,3),2]) 

outflow_plot_20_grid

mob_indicators_out_22 <- mob_indicators_out %>% 
  filter(year == 2022)

outflow_plot_22_grid <- ggplot(data = mob_indicators_out_22, aes(fill = new_jenk_class )) +
  geom_sf(col = "white", size = .2) + 
  coord_sf() +
  scale_fill_brewer(palette = "OrRd", direction = 1) +
  theme_map() +
  theme(plot.title = element_text(size = 40, face = "bold"),
        legend.position = "right") +
  labs(title = "(d) Mexico City: Outflows 2022",
       fill = "Number of moves") +
  geom_sf(data = adm_shp,
          col = "gray", 
          size = .7,
          fill = "transparent") 
  # geom_sf(data = mob_indicators_1_22 %>%
  #            filter(REGION == "Metropolitana de Santiago"),  # Filter for Santiago municipality
  #         aes(fill = "black"),  # Set a custom fill for the highlighted municipality
  #         col = "black",                 # Set the border color for Santiago
  #         size = 1.5,                  # Adjust the border size
  #         fill = "transparent") +
  # coord_sf(xlim = st_coordinates(bbox_new)[c(1,2),1], 
  #          ylim = st_coordinates(bbox_new)[c(2,3),2]) 

outflow_plot_22_grid

```
```{r}
 plot_grid <- (inflow_plot_20_grid + inflow_plot_22_grid) / (outflow_plot_20_grid + outflow_plot_22_grid)
```

```{r}
plot_grid
```

```{r}
png("R:\\outputs\\maps\\mex_flows_wgrid.png", units="in", width=10, height=6, res=300)
plot_grid
dev.off()
```
